from pathlib import Path


CONFIG = {
    "data_root": Path("data"),
    "out_dir": "runs/celeba_meanflow",
    "resume": None,
    "device": "cuda",
    "distributed": True,
    "checkpoint": "runs/celeba_meanflow/model_final.pt",
    "sample_output": "runs/celeba_meanflow/samples.png",
    "trajectory_output": "runs/celeba_meanflow/trajectory.png",
    "trajectory_columns": 6,
    "image_size": 64,
    "batch_size": 10,
    "base_channels": 192,
    "steps": 100000,
    "lr": 2e-4,
    "weight_decay": 1e-4,
    "grad_clip": 1.0,
    "workers": 4,
    "amp": True,
    "log_every": 50,
    "sample_every": 1000,
    "sample_steps": 50,
    "sample_n": 16,
    "ckpt_every": 50000,
    "seed": 42,
    "eval_batches": 100,
    "eval_output": "runs/celeba_meanflow/eval.json",
}
