CONFIG = {
    "data_root": "./data",
    "out_dir": "./runs/celeba_flow",
    "image_size": 64,
    "batch_size": 64,
    "base_channels": 64,
    "steps": 10000,
    "lr": 2e-4,
    "weight_decay": 1e-4,
    "grad_clip": 1.0,
    "workers": 4,
    "device": None,
    "amp": True,
    "log_every": 100,
    "sample_every": 1000,
    "sample_steps": 100,
    "sample_n": 16,
    "ckpt_every": 5000,
}
